# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-14 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180814_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailveriyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u5fd8\u8bb0\u5bc6\u7801'), ('update_email', '\u66f4\u65b0\u90ae\u7bb1')], max_length=20),
        ),
    ]
