# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-15 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180814_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=100, verbose_name='\u987a\u5e8f'),
        ),
    ]
